### ISSUE TITLE
Verify that all files for executing prediction are on Git

### ISSUE THREAD

**Issue by iparask** [iceberg-project/Rivers#9]
For @samiradaneshgar  to verify that all files are on Git.

For @iparask to execute on Bridges

**Comment by bspitzbart** [comment]
@samiradaneshgar Is the current 3-band code on github?  Are 3-band test images on Google drive?

**Comment by samiraucsb** [comment]
@bspitzbart I uploaded all the prediction related codes to Rivers/src/classification/. Also, test images and the weights are on the Google drive. @iparask and @bspitzbart we can Zoom at your convenience so I can go through what I have uploaded.

**Comment by bspitzbart** [comment]
@samiradaneshgar Sure, can we do 3 pm ET (12 PT) today or tomorrow?

**Comment by iparask** [comment]
Sure! Thank you @samiradaneshgar

**Comment by samiraucsb** [comment]
@bspitzbart and @iparask Thank you! I am available today if it works for both of you.

**Comment by bspitzbart** [comment]
That works for me.

**Comment by iparask** [comment]
> That works for me.

Me too

**Comment by bspitzbart** [comment]
Great. We can use the regular number at 3:00 ET.
https://zoom.us/j/499136917

**Comment by iparask** [comment]
I think this can be closed.
